LN26:P and NP problem
colinaaa/algorithm-course-notes pull request #27
Opened 2020-12-18 14:59 UTC by shangkaiyuan

P和NP问题提交

2020-12-18 16:34 UTC, colinaaa requested changes
留了蛮多问题，辛苦改一下吧，不明白的ping我

2020-12-18 16:34 UTC, colinaaa commented on src/Ln26-P-NP.tex
> +	$P$代表$Polynomial$，指存在多项式复杂度的算法的问题。
这里为什么要用把 Polynomial写在数学公式里？

如果想用强调可以写 `\textit{Polynomial}` 或者 `\emph{Polynomial}`

2020-12-18 16:34 UTC, colinaaa commented on src/Ln26-P-NP.tex
> +	$NP$代表$Non-deterministic Polynomial$，指可以在多项式时间内验证一个解，或有一个多项式时间的非确定性算法的问题。
同上

2020-12-18 16:34 UTC, colinaaa commented on src/Ln26-P-NP.tex
> +	$NPC$代表$Non-deterministic Polynomial Complete$，指满足以下两个条件的问题:
同上，用 `\textit{Polynomial}` 或者 `\emph{Polynomial}`

2020-12-18 16:34 UTC, colinaaa commented on src/Ln26-P-NP.tex
> +	为了更好的阐述这种关系，我们采用它们之间的关系图来对此进行描述，如下图：
这里可以不用“下图”吧，用一下`\autoref`吧，下面图片加一下label

2020-12-18 16:34 UTC, colinaaa commented on src/Ln26-P-NP.tex
> +		(1)如果$X\leq_pY$且$Y$能在多项式时间内求解，则$X$也能在多项式时间内求解。\\
这里的1，2，3，4用itemize环境好一点

2020-12-18 16:34 UTC, colinaaa commented on src/Ln26-P-NP.tex
> +		(1)如果$X\leq_pY$且$Y$能在多项式时间内求解，则$X$也能在多项式时间内求解。\\
或者enumerate环境更好

2020-12-18 16:34 UTC, colinaaa commented on src/Ln26-P-NP.tex
> +\end{itemize}
这里为什么不把三个环境合并？

2020-12-18 16:34 UTC, colinaaa commented on src/Ln26-P-NP.tex
> +\begin{itemize}
同上，可以合并一下三个环境

2020-12-18 16:34 UTC, colinaaa commented on src/Ln26-P-NP.tex
> +过程见下图：
同autoref

2020-12-18 16:34 UTC, colinaaa commented on src/Ln26-P-NP.tex
> +过程见下图：
同autoref

2020-12-18 16:34 UTC, colinaaa commented on src/Ln26-P-NP.tex
> +	\item a)$P_1\leq_pP_2$
这里用嵌套的enumerate环境或者嵌套的itemize环境吧（可以相互嵌套的）

2020-12-18 16:34 UTC, colinaaa commented on src/Ln26-P-NP.tex
> +\end{itemize}
同合并环境

2020-12-18 16:34 UTC, colinaaa commented on src/Ln26-P-NP.tex
> +	\item $NPC$问题的证明思路
这里感觉用paragraph更合适，不是很像itemize的用法

2020-12-18 16:41 UTC, shangkaiyuan commented
真是辛苦您了，我这就去改一下

2020-12-18 18:18 UTC, shangkaiyuan commented
第一次检查失败的原因是不小心在前一个有bug的版本上做了修改，有些bug还没修复，修复后就又提交了两次改了些bug

2020-12-19 03:33 UTC, shangkaiyuan commented
我看了一下，问题应该都改了，还有啥建议吗

2020-12-19 14:44 UTC, colinaaa approved these changes
LGTM.

2020-12-19 14:45 UTC, merged