近似算法（Ln15，放在最后的章节）
colinaaa/algorithm-course-notes pull request #32
Opened 2020-12-20 15:13 UTC by LMA936

2020-12-20 15:41 UTC, colinaaa requested changes
提了几个小点，可以改一下（表格那个是硬伤 其他的还好）

2020-12-20 15:41 UTC, colinaaa commented on src/Ln15-ApproximationAlgorithm.tex
> +\raggedright%网络流之图像分割的老哥用了个\centering害人不浅
我用括号括起来了，这种问题可以来提 issue的（像 #26 一样）

2020-12-20 15:41 UTC, colinaaa commented on src/Ln15-ApproximationAlgorithm.tex
> +证明：
有个proof环境，感觉会好看一点

2020-12-20 15:41 UTC, colinaaa commented on src/Ln15-ApproximationAlgorithm.tex
> +	\end{table}
最后一行好像乱了吧

![image](https://user-images.githubusercontent.com/40660121/102717293-5c342a80-431c-11eb-93c9-c9123156ed78.png)

2020-12-20 15:41 UTC, colinaaa commented on src/Ln15-ApproximationAlgorithm.tex
> +证明：
这里也用一下proof环境吧

2020-12-20 15:41 UTC, colinaaa commented on src/Ln15-ApproximationAlgorithm.tex
> +证明：
同proof环境

2020-12-20 15:41 UTC, colinaaa commented on src/Ln15-ApproximationAlgorithm.tex
> +	\item 注意这里的分子并不是ALG，而是ALG的期望
可以用一下remark环境

2020-12-21 00:21 UTC, LMA936 commented on src/Ln15-ApproximationAlgorithm.tex
> +\raggedright%网络流之图像分割的老哥用了个\centering害人不浅
有这种事（捂脸）

2020-12-21 06:08 UTC, colinaaa requested changes
proof应该是没有label的，需要删掉

2020-12-21 06:08 UTC, colinaaa commented on src/Ln15-ApproximationAlgorithm.tex
> +\begin{proof}{}{proof1:15Ln}
proof应该是没有label的

2020-12-21 06:08 UTC, colinaaa commented on src/Ln15-ApproximationAlgorithm.tex
> +\begin{proof}{}{proof2:15Ln}
同上，可以删掉这个lable

2020-12-21 06:08 UTC, colinaaa commented on src/Ln15-ApproximationAlgorithm.tex
> +\begin{proof}{}{proof3:15Ln}
同删掉label

2020-12-21 07:53 UTC, colinaaa approved these changes
LGTM.

2020-12-21 07:54 UTC, merged